### ISSUE TITLE
Duplicates on drag and drop

### ISSUE THREAD

**Issue by ghost** [asbjornenge/react-drag-and-drop#1]
Rapid-fire drag-and-dropping causes duplication of items (in Chrome 41.0.2272.101).

**Comment by asbjornenge** [comment]
@persille :+1: What do you mean by rapid-fire? Just doing it fast?

**Comment by ghost** [comment]
That's what she said. Yes :rabbit2:

**Comment by asbjornenge** [comment]
Hahahahahaha!!! :rocket: I'll look into it :grin:

**Comment by asbjornenge** [comment]
Klarer ikke å reprodusere denne. Tror det har med implementasjon i appen å gjøre, og ikke biblioteket. Lukker foreløpig.
