### ISSUE TITLE
Drag/Drop across classes

### ISSUE THREAD

**Issue by GCAT01** [asbjornenge/react-drag-and-drop#12]
I am VERY new to React/JS. I am also trying to crank out an app for a school project. I have draggable buttons (as their own React component) and areas where they can be dropped (in a separate component). I was trying to use the "data" feature to pass the value of the button to the dropped area, but it does not seem to be working. I noticed in all of your examples that the draggable and droppable objects are always under the same React component. Is this necessary for the "data" feature to work? Thanks!

**Comment by asbjornenge** [comment]
@YalithKBK hi! No, the `draggable` and the `droppable` does not need to be under the same component. Make sure you are using the `type` field on boths ends. Also; this component does not work on mobile, so make sure you test and build for desktop application.

If you want, feel free to share your `draggable` and `droppable` components here, and I can take a look :smile:

**Comment by azz0r** [comment]
Heads up, I got react-drag-and-drop working with mobile: https://github.com/azz0r/wwe-draft-generator/commit/615055aded4fa65ff25a7169a030caca76506abd

Shims this in basically: https://github.com/Bernardo-Castilho/dragdroptouch

**Comment by GCAT01** [comment]
Thanks for getting back to me. Luckily, this isn't a mobile project, so now worries there. Let's start with the drag/drop pieces themselves and makes sure I have those right:
```
             
              <Draggable type = 'column button' data = {this.props.value}>      
			<button className={classname} onClick={()=>this.click()}>
        		       {this.props.value}
      		        </button>
		</Draggable>

		<Droppable type = 'column button' onDrop = {this.handleDrop.bind(this)}>
			{this.state.value}
		</Droppable>

	      handleDrop(data) {
		console.log('data is ', data);
	      }
```

Am I using those types correctly?  
I should say also that when I run my code, the console output is "data is null".

**Comment by educastellano** [comment]
the prop `type` in `<Droppable>` should be `types` and accept an array:

```
<Droppable types={['column button']} ...>
```

Also, don't forget to set a `height` to Droppable, otherwise you won't have any area to drop the elements.

**Comment by GCAT01** [comment]
One more newbie question. I changed the "types" to an array and now something is being passed. My handleChange function is now getting the entire dropped object. From your example in the ReadMe, I thought giving it the parameter "data" would just return the data portion. Is there another way I should be doing this? My console output is:
`Object {column button: "Fifth Line"}`
All I want is the string "Fifth Line"

**Comment by educastellano** [comment]
Just:
```js
console.log('data is ', data['column button']);
```

But try to avoid spaces...

**Comment by asbjornenge** [comment]
I'm just going to close this now :smile: 

@azz0r feel free to add that mobile thing as a note in README :grin: :tada:
