### ISSUE TITLE
Request: enabled prop for Droppable 

### ISSUE THREAD

**Issue by azz0r** [asbjornenge/react-drag-and-drop#13]
Draggable has enabled but Droppable does not.

Would be quite a minor change with a big pay off :)

**Comment by asbjornenge** [comment]
Taking a stab at this one. Should `enabled={false}` disable `onDrag*` too? Or only `onDrop` ?

I'll try to build out a better test spec too. Enzyme helps!

//cc @azz0r

**Comment by azz0r** [comment]
Good question, I think both as you'd essentially be locking it but perhaps it could be granular?

**Comment by asbjornenge** [comment]
@azz0r Let's just disable them all for now, and see if we get issues. I have it implemented [here](https://github.com/asbjornenge/react-drag-and-drop/tree/droppable-enabled) - care to take a look at the diff? I even have tests :smile:

//cc @educastellano

**Comment by azz0r** [comment]
Sorry for the delay responding, I think it looks great!

**Comment by educastellano** [comment]
@asbjornenge it looks good to me, good job with the tests 🎉

**Comment by asbjornenge** [comment]
Out @ 2.3.0 :tada: Sorry it took forever :stuck_out_tongue:
