### ISSUE TITLE
Used with TypeScript 

### ISSUE THREAD

**Issue by pbpraveen1988** [asbjornenge/react-drag-and-drop#14]
Hello @asbjornenge ,

Can you please provide the @typedef of the library because i want to implement this with my project.
Please help me on this.

Thank You

**Comment by asbjornenge** [comment]
Sorry friend. I don't use TypeScript and don't want any typedef in my code. Feel free to fork and provide a `react-drag-and-drop-ts` :package: :smile: :+1:
