### ISSUE TITLE
React Components as Droppable Containers?

### ISSUE THREAD

**Issue by pbpraveen1988** [asbjornenge/react-drag-and-drop#15]
Hello,

I really liked your library , can we bind the Droppable property to React Component to become the Droppable containers instead of putting under the Droppable container.

Thank You

**Comment by asbjornenge** [comment]
@pbpraveen1988 version `2.4.0` added the `wrapperComponent` property. Check out the tests for how it can be used. Is this what you mean?

**Comment by praWINK** [comment]
@asbjornenge Thank you so much for one of the best npm package (drag-and-drop) you provided to us.My doubt is it possible to drop one component to another, at the same time remaining components will adjust itself???. I like to share one more information to you, in your npm package droppable start tag is not closed.`<Droppable
                types={['fruit']} 
                onDrop={this.onDrop.bind(this)}
                <ul className="Smoothie"></ul>
            </Droppable>`
