### ISSUE TITLE
Precompiled source?

### ISSUE THREAD

**Issue by peterugh** [asbjornenge/react-drag-and-drop#20]
I'm working in an ecosystem that doesn't support npm modules. I've compiled from source but the outputted file is asking for `require` which I don't have in the build pipeline. Can someone point me to an es5 compiled version that I can include with a `<script>` tag old school style?

**Comment by asbjornenge** [comment]
@peterugh you need to look into building to as an `umd` module. Take a look here: https://github.com/umdjs/umd I'm pretty sure both `browserify` and `webpack` can spit that out, but you need to configure what to ignore, so that it won't bundle the whole `React` code into the bundle 😛
