### ISSUE TITLE
sample code not working

### ISSUE THREAD

**Issue by vgurnani-systango** [asbjornenge/react-drag-and-drop#22]
I have copied the source code provided by you guys in documentation but getting error
```
import { Draggable, Droppable } from 'react-drag-and-drop'

class App extends React.Component {
    render() {
        <div>
            <ul>
                <Draggable type="fruit" data="banana"><li>Banana</li></Draggable>
                <Draggable type="fruit" data="apple"><li>Apple</li></Draggable>
                <Draggable type="metal" data="silver"><li>Silver</li></Draggable>
            </ul>
            <Droppable
                types={['fruit']} // <= allowed drop types
                onDrop={this.onDrop.bind(this)}>
                <ul className="Smoothie"></ul>
            </Droppable>
        </div>
    }
    onDrop(data) {
        console.log(data)
        // => banana 
    }
}
```

ERROR-
A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object. + react-drag and drop

Any help would be great.
Thanks for making this and any help in advance.

**Comment by azz0r** [comment]
Export default class App?

**Comment by vgurnani-systango** [comment]
Thanks for the reply but I am exporting the class like-

export default App

**Comment by asbjornenge** [comment]
@vgurnani-systango This is more of React error than specific to this package, so try google the error message or check stackoverflow 😄👍
