### ISSUE TITLE
multiple targets

### ISSUE THREAD

**Issue by charlesondr** [asbjornenge/react-drag-and-drop#26]
is there any feature available for multiple targets (droppable)

**Comment by azz0r** [comment]
Yeah just have multiple droppables

**Comment by charlesondr** [comment]
Hi,
Thanks for the support but i would need not that functionality.

Yes, i know already multiple droppable is available but what's my requirement is the drag should not disappear once the item is dropped.


![example](https://user-images.githubusercontent.com/26412540/26978276-8f7fe906-4d48-11e7-8607-c6c336972597.JPG)


Here,
Column 1 - is Dragable
Column 2 & 3 - is Dropable

Therefore, the scenario in this example is i can drag any item from column1 and then can drop into column 2 and 3. So once the item is dragged from the column 1 the lists should not get empty after dropping into column 2 and column 3. Also i can drag the same item in column1 and drop into column2 & 3.

**Comment by charlesondr** [comment]
Hi Aaron,

Any update on this query:
https://github.com/asbjornenge/react-drag-and-drop/issues/26



Thanks
Rakesh.R

**Comment by educastellano** [comment]
@charlesondr This is something you have to manage yourself. On the onDrop() event you get the data that has been dropped and you decide what to do with that, either keep or remove the draggable element.
