### ISSUE TITLE
How to send JSON data in Draggable data?

### ISSUE THREAD

**Issue by lintelbeam** [asbjornenge/react-drag-and-drop#29]
for example
let slotInfo = {
      name: slot.category.name,
      slotid: slot.id
}
 <Draggable type="category" data={slotInfo} className="child-category">

**Comment by azz0r** [comment]
```js
  onDrop(brand, wrestler) {
    //
  }

 <Droppable
        key={this.props.id}
        className="brand"
        types={[
          "wrestler",
        ]}
        onDrop={this.onDrop.bind(this, this.props)}>
```

**Comment by lintelbeam** [comment]
you need to JSON.stringify(obj) or use some reference value like an id if you can't stringify.
