### ISSUE TITLE
How can I remove one node?

### ISSUE THREAD

**Issue by isaacdeveloper** [asbjornenge/react-drag-and-drop#3]
Hi, is there any way to remove a node that is in "droppable"?

**Comment by asbjornenge** [comment]
I'm not quite sure I understand the question. You remove a droppable like you would remove any other React component. Could you elaborate? Are you unsure how to remove a React component? You usually have a list of some data that you display, so you need to filter this list before you render.

**Comment by isaacdeveloper** [comment]
I mean an item that is already in the "droppable" component can be removed from that list.

**Comment by asbjornenge** [comment]
@isaacanet this react component is not concerned with what is renderen in the `droppable` component. That is up to your React code. This library only supplies "wrapper components" that will submit events when a `draggable` is dropped in a suitable `droppable`. How you handle those events or what you wish to render in you `droppable` component is up to you. For React support check out the [ReactJS website](https://facebook.github.io/react/).
