### ISSUE TITLE
Possible to disable Click or assign another element for Clicking instead of the entire droppable area?

### ISSUE THREAD

**Issue by jammind** [asbjornenge/react-drag-and-drop#41]
I want my entire view to accept dropped files but only a small button to click and upload files. Right now, any click in the view will bring up the file chooser and interrupt the original interaction.

**Comment by educastellano** [comment]
@jammind Feel free to send a PR. You probably also want to update packages since this hasn't maintained for a while.

**Comment by jammind** [comment]
Thank you for the significant work. I would also like to add a prop to handle the uploading state and fix the overlapped "Drop here" with the enclosed elements. But I will keep the interface 100% compatible with the original. If you feel good, I can send a PR when it's ready.

**Comment by educastellano** [comment]
Sounds good

**Comment by jammind** [comment]
I have cloned your repo. Applied my updates with comments. When I tried to push to the repo, it says
```
ERROR: Permission to KarimMokhtar/react-drag-drop-files.git denied to jammind.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
Shall I become a contributor first and how?
